package juna;

import java.util.ArrayList;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "UserInfo")
public class UserInfo {

    private String id;
    private String email;
    private List<String> trainIds;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public String getEmail() {
        return email;
    }

    @DynamoDBAttribute
    public List<String> getTrainIds() {
        return trainIds;
    }

    // standard setters/constructors
    public UserInfo() {
    }
    
    public UserInfo(String email) {
        this.email = email;
        this.trainIds = new ArrayList<>();
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    public void setTrainIds(List<String> trainIds) {
        this.trainIds = trainIds;
    }
 
}