package juna;

import java.util.ArrayList;
import java.util.List;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotBlank;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "UserInfo")
public class UserInfo {

    private String id;

    @NotNull
    @Email
    @NotBlank
    private String email;

    @NotNull
    @Size(min=1)
    private List<String> trainIds;
    
    private String approvalPending;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public String getEmail() {
        return email;
    }

    @DynamoDBAttribute
    public List<String> getTrainIds() {
        return trainIds;
    }

    @DynamoDBAttribute
    public String getApprovalPending() {
        return approvalPending;
    }

    // standard setters/constructors
    public UserInfo() {
    }

    public UserInfo(String email) {
        this.email = email;
        this.trainIds = new ArrayList<>();
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setTrainIds(List<String> trainIds) {
        this.trainIds = trainIds;
    }

    public void setApprovalPending(String approvalPending) {
        this.approvalPending = approvalPending;
    }
 
}